```{r}
Sys.setlocale(locale = "chs")
#install.packages("xlsx")
require("xlsx")
#install.packages("stringr")
require(stringr)
#install.packages("readr")
require(readr)
#install.packages("dplyr")
require(dplyr)
#install.packages("plyr")
require(plyr)
#install.packages("zoo")
require(zoo)
#install.packages("scales")
require(scales)
#install.packages("tseries")
require(tseries)
#install.packages("forecast")
require(forecast)
# install.packages("tidyverse")
# require(tidyverse)
```

Read data
```{r}
data <- read.xlsx("非洲通讯产品销售数据.xlsx", 'SalesData', header=TRUE)
data2 <- read.xlsx("非洲通讯产品销售数据.xlsx", 'SalespersonData', header=TRUE)
```

Pre-processing
```{r}
data_1 <- data
data_1$日期 <- format(as.Date(data_1$日期,format="%Y-%m-%d"),"%Y-%m")

month <- format(seq(as.Date("2017/01/01"),as.Date("2020/12/31"),"months"),"%Y-%m")
month <- as.data.frame(month)
colnames(month) <- "日期"
data_1_1 <- data.frame(data$国家,data$城市,data$地区,data$服务分类)
colnames(data_1_1) <- c('国家','城市','地区','服务分类')


data_1_2 <- merge(x=month,y=data_1_1)
data_1_2 <- unique(data_1_2)

data_1_2 <- merge(x=data_1_2,y=data_1,all.x = TRUE)
data_1_2[is.na(data_1_2)] <- 0

data_1_3 <- data_1_2
year_data <- data_1_3$日期
year_data <- format(as.Date(as.yearmon(year_data),format="%Y-%m-%d"),"%Y")
data_1_3$年度 <- year_data
data_1_3$季度 <- as.character(data_1_3$日期)
data_1_3$季度[which(format(as.Date(as.yearmon(data_1_3$日期),format="%Y-%m-%d"),"%m") %in% c("01","02","03"))] <- '第一季度'
data_1_3$季度[which(format(as.Date(as.yearmon(data_1_3$日期),format="%Y-%m-%d"),"%m") %in% c("04","05","06"))] <- '第二季度'
data_1_3$季度[which(format(as.Date(as.yearmon(data_1_3$日期),format="%Y-%m-%d"),"%m") %in% c("07","08","09"))] <- '第三季度'
data_1_3$季度[which(format(as.Date(as.yearmon(data_1_3$日期),format="%Y-%m-%d"),"%m") %in% c("10","11","12"))] <- '第四季度'

#output csv for dashboard
data_2 <- ddply(data_1_3, .(年度,季度,地区,国家,服务分类 ), summarise, 各国销售额=sum(销售额),各国利润=sum(利润))
data_2_1 <- ddply(data_1_2,.(日期,地区,国家), summarise, 各国销售额=sum(销售额),各国利润=sum(利润))
#write.xlsx(data_2_1,'quarter.xlsx',row.names = F)
data_2_4 <- ddply(data_1_2,.(日期,地区,国家,服务分类 ), summarise, 各国销售额=sum(销售额),各国利润=sum(利润))
data_2_4$日期 <- as.yearqtr(as.Date(as.yearmon(data_2_4$日期),format="%Y-%m-%d"),format = "%Y-%m-%d")

data_2_2 <- ddply(data_1_2,.(日期,地区,国家,服务分类), summarise, 各国销售额=sum(销售额),各国利润=sum(利润))
#write.xlsx(data_2_2,'quarter2.xlsx',row.names = F)
```

Task1.1
```{r}
data_3 <- ddply(data_1_3, .(年度,地区,国家,服务分类 ), summarise, 各国销售额=sum(销售额),各国利润=sum(利润))

#percentage calculate function
profit_pct_change <- function(x) {
  x <- x[order(x$年度, decreasing = TRUE), ] # Confirms ordered by decreasing year
  销售增长率 <- -diff(x$各国销售额)/x$各国销售额[-1]  # Gets percent change in profit from preceding year
  利润增长率 <- diff(x$各国利润)/x$各国利润[-1] 
  data.frame(year = x$年度[-length(x$年度)], 销售增长率 = 销售增长率, 利润增长率=利润增长率) # Returns data frame
}

#percentage calculate
g <-data_3 %>% 
  group_by(地区,国家,服务分类) %>%
  do(profit_pct_change(.))

colnames(g) <- c("地区","国家","服务分类","年度","销售增长率","利润增长率")

#merge percentage data frame with original data
task1_1 <- merge(x=g,y=data_3,all = TRUE)
task1_1 <- data.frame(task1_1$年度,task1_1$地区,task1_1$国家,task1_1$服务分类,task1_1$各国销售额,task1_1$销售增长率,task1_1$各国利润,task1_1$利润增长率)
task1_1[is.na(task1_1)] <- 0
colnames(task1_1) <- c("年度","地区","国家","服务分类","各国销售额","销售增长率","各国利润","利润增长率")

#Clear infinite
task1_1$销售增长率[which(is.infinite(task1_1$销售增长率))] <- 0
task1_1$利润增长率[which(is.infinite(task1_1$利润增长率))] <- 0

#output result named task1_1
write.csv(task1_1,"../result/result1/task1_1.csv",row.names = F)
```

Task1.2
```{r}
task1_2 <- ddply(data_1 , .(地区,国家,服务分类 ), summarise, 销售额=sum(销售额),利润=sum(利润))

#output result named task1_2
write.csv(task1_2,"../result/result1/task1_2.csv",row.names = F)
```

Task1.3
```{r}
data2_1 <- ddply(merge(data2, unique(data2$销售经理)), 
  .(销售经理), summarise, 销售合同=(sum(销售合同)/10),成交率=paste(mean(成交率)*100,"%"))

#short by highest sales
task1_3 <- data2_1[order(desc(data2_1$销售合同)),]
row.names(task1_3) <- c(1:nrow(task1_3))

#output result named task1_3
write.csv(task1_3,"../result/result1/task1_3.csv",row.names = F)

```

Task1.4
```{r}
#build prediction model 
prediction_model <- data_2_4 %>% group_by(地区,国家,服务分类) %>% do(data.frame(
        销售额预测 = forecast(auto.arima(ts(.$各国销售额,start=c(2017,1),
                                            end=c(2020,12),frequency=12)), level=c(95),h=1*1),
        利润预测 = forecast(auto.arima(ts(.$各国利润,start=c(2017,1),
                                            end=c(2020,12),frequency=12)), level=c(95),h=1*1)))

#extract result to a new data frame
task1_4 <- data.frame(prediction_model$地区,prediction_model$国家,prediction_model$服务分类,prediction_model$销售额预测.Point.Forecast,prediction_model$利润预测.Point.Forecast)
colnames(task1_4) <- c("地区","国家","服务分类","销售额预测","利润预测")
#round up the prediction
task1_4$销售额预测 <- round(task1_4$销售额预测,4)
task1_4$利润预测 <- round(task1_4$利润预测,4)

#output result named task1_4
write.csv(task1_4,"../result/result1/task1_4.csv",row.names = F)
```

